name: Azure Pages CI
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize, reopened, edited, closed]
    branches:
    - master

jobs:
  azure_pages_build_and_upload_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Azure Pages Build And Deploy
    steps:
    - uses: actions/checkout@v1
    - shell: bash
      run: |
        npm install
        npm run build
    - uses: joslinmicrosoft/staticsitesaction@master
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN }}
        action: 'upload'         
        app_artifact_location: 'app'
        api_artifact_location: 'api'
  
  azure_pages_close_pr_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Azure Pages Close Pull Request Job
    steps:
    - uses: joslinmicrosoft/staticsitesaction@master
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN }}
        action: 'close'
